Copy SSH private/public files instead of symlink
Error: Forbidden path outside the build context: busybee ()
See: https://github.com/docker/compose/issues/1398